[project]
name = "classcard-hack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "httpx>=0.28.1",
    "selenium>=4.31.0",
    "toml>=0.10.2",
    "typer>=0.15.2",
]
